# Generated by Django 3.1.3 on 2020-11-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=100)),
                ('choice1', models.TextField(max_length=100)),
                ('choice2', models.TextField(max_length=100)),
                ('choice3', models.TextField(max_length=100)),
                ('choice4', models.TextField(max_length=100)),
                ('choice5', models.TextField(max_length=100)),
            ],
        ),
    ]
